---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: backend
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: backend
    template:
      metadata:
        labels:
          app: backend
      spec:
        containers:
        - name: backend
          image: albertom/k8sdemo_backend
          ports:
          - containerPort: 8080
          env:
            - name: K8SDEMO_BACKEND_PORT
              value: "8080"

---
  apiVersion: v1
  kind: Service
  metadata:
    name: backend
  spec:
    selector:
      app: backend
    ports:
    - port: 8080
      protocol: TCP
